baseURL  =  "https://flynx.dev"

defaultContentLanguage="zh-cn"
[languages.en]
languageCode = "en"
[languages.zh-cn]
languageCode = "zh-cn"
# DefaultContentLanguage = "zh-cn"
title  =  "飞天"
subtitle = "设计之妙，存乎一心；去伪存精，化繁为简"

theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
# 每页显示的文章数量用于分页
paginate =  10
# rss 输出数量
rssLimit = 5

[permalinks]
  posts = "/:filename/"
  tags = "/tags/:slug/"

[menu]
  [[menu.main]]
	name="阅读"
	url="/books/"
	weight="1"
  [[menu.main]]
  name="观影"
  url="/movies/"
  weight="2"
  [[menu.main]]
  name="相册"
  url="/photos/"
  weight="3"
  [[menu.main]]
  name="归档"
  url="/archives/"
  weight="4"
  [[menu.main]]
  name="关于"
  url="/about/"
  weight="5"

[params]

  # toc on post
  toc = true
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/lmm214/immmmm/edit/master/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.valine]
    enable = false
    appId = 'm6rxiyixBDG25mYPEPapQpnR-MdYXbMMI'
    appKey = 'WMokwNAwh9noJ4XeUjVBjsCt'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true
    serverURLs = "https://m6rxiyix.api.lncldglobal.com"

[params.twikoo]
	enable = true
